language: node_js
node_js:
  - "12"
cache:
  directories:
  - node_modules
script:
  - npm run build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token
  local_dir: dist/work-online
  on:
    branch: master